<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1586241911128' stop='1586241916809'>
    <name>Demo Test case</name>
    <title>Demo Test case</title>
    <test-cases>
        <test-case start='1586241911129' status='failed' stop='1586241916207'>
            <name>addition test</name>
            <title>addition test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected '28' to equal 28.</message>
                <stack-trace>Error: Failed expectation
                    at homepage.verifyResult (D:\IVL\AutoDocs\Protractor\Projects\ProtractorDemo\pages\homepage.js:26:34)
                    at UserContext.&lt;anonymous> (D:\IVL\AutoDocs\Protractor\Projects\ProtractorDemo\tests\calculator.js:27:18)
                    at C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27</stack-trace>
            </failure>
        </test-case>
        <test-case start='1586241916207' status='failed' stop='1586241916808'>
            <name>substraction test</name>
            <title>substraction test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>ReferenceError: fs is not defined</message>
                <stack-trace>ReferenceError: fs is not defined
                    at D:\IVL\AutoDocs\Protractor\Projects\ProtractorDemo\conf\conf.js:86:28
                    at ManagedPromise.invokeCallback_ (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\abhishek.mishra\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>